// Structural dictionary type — all leaf values must be strings
export interface Dict {
  nav: {
    dashboard:      string;
    trends:         string;
    simulations:    string;
    conversational: string;
    coaching:       string;
    leaderboard:    string;
    org:            string;
    activities:     string;
  };
  kpi: {
    totalSimulations: string;
    uniqueUsers:      string;
    avgScore:         string;
    passRate:         string;
    activeDays:       string;
    totalActivities:  string;
  };
  filters: {
    dateRange:  string;
    activities: string;
    diagnosis:  string;
    reset:      string;
    all:        string;
    passed:     string;
    failed:     string;
    quick:      string;
    monthly:    string;
    weekly:     string;
    presets: {
      last7d:    string;
      last30d:   string;
      last3m:    string;
      last6m:    string;
      thisMonth: string;
      allTime:   string;
    };
  };
  charts: {
    scoreTrend:        string;
    interactionFunnel: string;
    scoreDistribution: string;
    activityBreakdown: string;
    leaderboard:       string;
    scoreTrendSub:     string;
    interactionSub:    string;
    scoreDistSub:      string;
    activityUsage:     string;
    leaderboardSub:    string;
    avgScoreLabel:     string;
    passRateLabel:     string;
    simulationsLabel:  string;
    usersLabel:        string;
    interactionLabel:  string;
    rangeLabel:        string;
    percentageLabel:   string;
    periodsLabel:      string;
    noDataPeriod:      string;
    adjustFilters:     string;
    moreItems:         string;
    excellent:         string;
    good:              string;
    average:           string;
    critical:          string;
    simAbbrev:         string;
    simsByActivity:    string;
    avgScorePct:       string;
    passRatePct:       string;
    perUseCase:        string;
  };
  table: {
    id:         string;
    user:       string;
    activity:   string;
    date:       string;
    score:      string;
    diagnosis:  string;
    approved:   string;
    failed:     string;
    viewDetails: string;
    advisor:    string;
    performance: string;
    interactions: string;
    back:       string;
    history:    string;
  };
  ai: {
    copilot:     string;
    insights:    string;
    performance: string;
    coaching:    string;
    trends:      string;
    close:       string;
    generating:  string;
    noInsights:  string;
    achievement:       string;
    trend:             string;
    risk:              string;
    anomaly:           string;
    opportunity:       string;
    autoAnalysis:      string;
    noAlerts:          string;
    noAnomalies:       string;
    activeContext:     string;
    analyzingSims:     string;
    simsAnalyzed:      string;
    autoGenerated:     string;
    perfSummary:       string;
    bestActivity:      string;
    criticalActivity:  string;
    hardestRound:      string;
    monthTrendUp:      string;
    monthTrendDown:    string;
    needsCoaching:     string;
    belowMin:          string;
    withinRange:       string;
    optimal:           string;
    advisors:          string;
    vsPrevious:        string;
    coachingRec:       string;
    interactionNeedsReinforcement: string;
    noInteractionIssues: string;
    userAverage:       string;
    sessionHistory:    string;
    rank:              string;
  };
  auth: {
    login:          string;
    signup:         string;
    email:          string;
    password:       string;
    submit:         string;
    forgotPassword: string;
    resetPassword:  string;
    backToLogin:    string;
    noAccount:      string;
    hasAccount:     string;
    demoFill:       string;
  };
  common: {
    loading:  string;
    noData:   string;
    error:    string;
    back:     string;
    export:   string;
    previous: string;
    next:     string;
    page:     string;
    of:       string;
    showing:  string;
    results:  string;
    search:   string;
    live:     string;
    refresh:  string;
    active:   string;
    inactive: string;
    loadingSession: string;
    sessionNotFound: string;
  };
  scope: {
    title:           string;
    executive:       string;
    executiveSub:    string;
    supervisor:      string;
    admin:           string;
    participant:     string;
    selectScope:     string;
    allOrg:          string;
    teamSize:        string;
    participants:    string;
    admins:          string;
    supervisors:     string;
    noData:          string;
    viewingAs:       string;
    switchView:      string;
    organization:    string;
    hierarchy:       string;
  };
}

export const es: Dict = {
  nav: {
    dashboard:      "Resumen",
    trends:         "Tendencias",
    simulations:    "Simulaciones",
    conversational: "Conversacional",
    coaching:       "Coaching IA",
    leaderboard:    "Leaderboard",
    org:            "Organización",
    activities:     "Actividades",
  },
  kpi: {
    totalSimulations: "Simulaciones",
    uniqueUsers:      "Usuarios Activos",
    avgScore:         "Puntaje Promedio",
    passRate:         "Tasa Aprobación",
    activeDays:       "Días Activos",
    totalActivities:  "Actividades",
  },
  filters: {
    dateRange:  "Rango de fechas",
    activities: "Actividades",
    diagnosis:  "Diagnóstico",
    reset:      "Limpiar",
    all:        "Todos",
    passed:     "Aprobados",
    failed:     "No aprobados",
    quick:      "Rápido",
    monthly:    "Mensual",
    weekly:     "Semanal",
    presets: {
      last7d:    "Últimos 7 días",
      last30d:   "Últimos 30 días",
      last3m:    "Últimos 3 meses",
      last6m:    "Últimos 6 meses",
      thisMonth: "Este mes",
      allTime:   "Todo el tiempo",
    },
  },
  charts: {
    scoreTrend:        "Tendencia de Rendimiento",
    interactionFunnel: "Rendimiento por Interacción",
    scoreDistribution: "Distribución de Puntajes",
    activityBreakdown: "Desglose por Actividad",
    leaderboard:       "Ranking de Asesores",
    scoreTrendSub:     "Evolución mensual del puntaje y tasa de aprobación",
    interactionSub:    "Tasa de aprobación en cada ronda conversacional",
    scoreDistSub:      "Frecuencia de calificaciones por rango",
    activityUsage:     "Uso por Actividad",
    leaderboardSub:    "Por puntaje promedio",
    avgScoreLabel:     "Puntaje promedio",
    passRateLabel:     "Tasa aprobación",
    simulationsLabel:  "Simulaciones",
    usersLabel:        "Usuarios",
    interactionLabel:  "Interacción",
    rangeLabel:        "Rango",
    percentageLabel:   "Porcentaje",
    periodsLabel:      "períodos",
    noDataPeriod:      "Sin datos para el período seleccionado",
    adjustFilters:     "Ajusta los filtros de fecha o actividad",
    moreItems:         "más",
    excellent:         "excelente",
    good:              "bueno",
    average:           "regular",
    critical:          "crítico",
    simAbbrev:         "sim.",
    simsByActivity:    "Simulaciones por actividad",
    avgScorePct:       "Puntaje promedio (%)",
    passRatePct:       "Tasa de aprobación (%)",
    perUseCase:        "por caso de uso",
  },
  table: {
    id:         "ID",
    user:       "Usuario",
    activity:   "Actividad",
    date:       "Fecha",
    score:      "Puntaje",
    diagnosis:  "Diagnóstico",
    approved:   "Aprobado",
    failed:     "No aprobado",
    viewDetails:"Ver detalles",
    advisor:    "Asesor",
    performance:"Rendimiento",
    interactions: "Interacciones",
    back:       "Atrás",
    history:    "Historial",
  },
  ai: {
    copilot:     "Copiloto IA",
    insights:    "Insights IA",
    performance: "Rendimiento",
    coaching:    "Coaching",
    trends:      "Tendencias",
    close:       "Cerrar",
    generating:  "Generando insights…",
    noInsights:  "Sin insights disponibles para el período seleccionado.",
    achievement:       "Logro",
    trend:             "Tendencia",
    risk:              "Riesgo",
    anomaly:           "Anomalía",
    opportunity:       "Oportunidad",
    autoAnalysis:      "Análisis automático del período",
    noAlerts:          "Sin alertas activas",
    noAnomalies:       "El sistema no detecta anomalías",
    activeContext:     "Contexto activo",
    analyzingSims:     "Analizando simulaciones en tiempo real",
    simsAnalyzed:      "simulaciones analizadas",
    autoGenerated:     "Insights generados automáticamente · Datos en tiempo real",
    perfSummary:       "Resumen de rendimiento",
    bestActivity:      "Mejor actividad",
    criticalActivity:  "Actividad crítica",
    hardestRound:      "es la más difícil",
    monthTrendUp:      "Tendencia mensual positiva",
    monthTrendDown:    "Tendencia mensual negativa",
    needsCoaching:     "asesores necesitan coaching",
    belowMin:          "Por debajo del umbral mínimo (50%).",
    withinRange:       "Dentro de rango, con margen de mejora.",
    optimal:           "Rendimiento óptimo.",
    advisors:          "asesores",
    vsPrevious:        "vs anterior",
    coachingRec:       "Recomendaciones de Coaching",
    interactionNeedsReinforcement: "requiere refuerzo",
    noInteractionIssues: "No se identificaron interacciones críticas en esta sesión.",
    userAverage:       "Promedio del asesor",
    sessionHistory:    "Historial de",
    rank:              "Rango global",
  },
  auth: {
    login:          "Iniciar sesión",
    signup:         "Crear cuenta",
    email:          "Correo electrónico",
    password:       "Contraseña",
    submit:         "Continuar",
    forgotPassword: "¿Olvidaste tu contraseña?",
    resetPassword:  "Restablecer contraseña",
    backToLogin:    "Volver al inicio de sesión",
    noAccount:      "¿No tienes cuenta?",
    hasAccount:     "¿Ya tienes cuenta?",
    demoFill:       "Rellenar con demo",
  },
  scope: {
    title:        "Vista organizacional",
    executive:    "Vista Ejecutiva",
    executiveSub: "Toda la organización Gentera",
    supervisor:   "Supervisor",
    admin:        "Admin",
    participant:  "Participante",
    selectScope:  "Seleccionar vista",
    allOrg:       "Toda la organización",
    teamSize:     "Tamaño de equipo",
    participants: "Participantes",
    admins:       "Admins",
    supervisors:  "Supervisores",
    noData:       "Sin datos para esta vista",
    viewingAs:    "Viendo como",
    switchView:   "Cambiar vista",
    organization: "Organización Gentera",
    hierarchy:    "Jerarquía",
  },
  common: {
    loading:    "Cargando…",
    noData:     "Sin datos",
    error:      "Error al cargar datos",
    back:       "Regresar",
    export:     "Exportar",
    previous:   "Anterior",
    next:       "Siguiente",
    page:       "Página",
    of:         "de",
    showing:    "Mostrando",
    results:    "resultados",
    search:     "Buscar",
    live:       "En vivo",
    refresh:    "Actualizar datos",
    active:     "Activo",
    inactive:   "Inactivo",
    loadingSession: "Cargando sesión…",
    sessionNotFound: "Sesión no encontrada",
  },
};
